### ISSUE TITLE
Error running "yarn run watch:example-shop" on new install

### ISSUE THREAD

**Issue by chrisnateys** [Jordaneisenburger/fallback-studio#18]
I have a Valet+ install of Magento 2.3.2 with the Venia Sample Data installed. I've referenced it in the src/example-company/example-shop/.env file:
`MAGENTO_BACKEND_URL=https://fallback.test/`
I've also added:
`NODE_TLS_REJECT_UNAUTHORIZED=0`
at the end of the file due to Valet's interesting relationship to SSL.

On a fresh install of PWA studio, this works. And to be fair, this worked on a fresh install of fallback that I tested earlier this week.

On a new install I created today, however, it does not. Instead, after running "yarn run watch:example-shop" I receive the following error:
`Chriss-MacBook-Pro:fallback-studio chrisnelson$ yarn run watch:example-shop
yarn run v1.13.0
$ yarn example-shop run watch
$ yarn workspace @fallback-studio/example-shop run watch
$ webpack-dev-server --progress --color --env.mode development
TypeError: Cannot read property '__schema' of undefined
    at getSchemaTypes.then.data (/Users/chrisnelson/fallback-studio/src/pwa-studio/packages/pwa-buildpack/lib/Utilities/graphQL.js:49:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
✨  Done in 3.65s.`

**Comment by chrisnateys** [comment]
This is clearly an issue with the Magento installation I was pulling data from, not with fallback studio. Closed!
